# yamllint disable rule:line-length
---

name: 'Checkout PR'

description: >-
  Checkout last commit from source repository

inputs:
  jobname:
    default: ${{ github.job }}
  token:
    description: 'A Github PAT'
    required: true

runs:
  using: "composite"
  steps:
    - name: 'Checkout PR branch last commit'
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ inputs.token }}
        fetch-depth: 1
        submodules: true
        lfs: true
