name: 'Upload Failed Job Logs'
description: 'On workflow job failure, fetch and send relevant logs with branch information to an external API'
author: 'Your Name'
inputs:
  run_id:
    description: 'Workflow run ID to fetch logs for (defaults to current run if not set)'
    required: false
  github_token:
    description: 'GitHub token for API access'
    required: true
runs:
  using: "composite"
  steps:
    - name: Fetch and send failed logs
      id: send_logs
      shell: bash
      run: bash ${{ github.action_path }}/log-collector.sh
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        TARGET_RUN_ID: ${{ inputs.run_id || github.run_id }}
        TARGET_REPO: ${{ github.repository }}
        GITHUB_REF: ${{ github.ref }}
