name: 'Calculate tests tags'

description: >-
  Calculates corresponding CI image tags based on github events for a group of tyk repositories

inputs:
  repo:
    description: Name of the repository where the workflow was triggered from
  github_event:
    description: Github event passed from main workflow
  github_ref:
    description: Github reference passed from main workflow
  github_base_ref:
    description: Github reference passed from main workflow
  build_sha:
    description: Github sha for referencing the build tag for ci image

outputs:
  tyk:
    description: "Tyk gateway ci image tag"
    value: ${{ steps.get-version.outputs.tyk }}
  tyk-analytics:
    description: "Tyk analytics ci image version"
    value: ${{ steps.get-version.outputs.tyk_analytics }}
  tyk-pump:
    description: "Tyk pump ci image version"
    value: ${{ steps.get-version.outputs.tyk_pump }}
  tyk-sink:
    description: "Tyk sink ci image version"
    value: ${{ steps.get-version.outputs.tyk_sink }}
  tyk-automated-tests:
    description: "Tyk automated tests ci image version"
    value: ${{ steps.get-version.outputs.tyk_automated_tests }}  
      
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - name: Calculate versions
      id: get-version
      shell: bash
      run: get_tags.sh ${{ inputs.repo }} ${{ inputs.github_event }} ${{ inputs.github_ref }} ${{ inputs.github_base_ref }} ${{ inputs.build_sha }}