# yamllint disable rule:line-length
---

name: "Run gotestsum"

description: >-
  Run gotestsum with retry options against all packages

inputs:
  jobname:
    default: ${{ github.job }}

  # Tags to include (csv)
  tags:
    default: ""

  # Arguments for `go test` (-race, etc.)
  args:
    defaults: ""

  # Loop through the packages
  loop:
    default: "yes"

  # Exclude some packages (grep pattern)
  exclude:
    default: "^$"

  # How many times to rerun a test on failure
  rerun:
    default: "1"

runs:
  using: "composite"
  steps:
    - name: "Run gotestsum on all packages"
      shell: "bash"
      if: ${{ inputs.loop != 'yes' }}
      run: |
        gotestsum --junitfile coverage-report.xml --rerun-fails=3 --raw-command \
        go test -tags=${{ inputs.tags }} ${{ inputs.args }} -json -timeout 15m -coverprofile=coverage-report.cov ./...

    - name: "Run gotestsum on each package"
      shell: "bash"
      if: ${{ inputs.loop == 'yes' }}
      run: |
        package=$(go list .)
        packages=$(go list ./... | tail -n +2 | sed -e "s|$package/||g" | egrep -v "${{ inputs.exclude }}")
        echo "Running tests for:"
        echo "$packages" | xargs -n1 echo '-'
        for pkg in ${packages}; do
            coveragefile=${pkg//\//-}
            gotestsum --junitfile ${coveragefile}.xml --rerun-fails=${{ inputs.rerun }} --raw-command \
            go test -tags=${{ inputs.tags }} ${{ inputs.args }} -json -timeout 15m -coverprofile=${coveragefile}.cov ./${pkg}
        done
