name: create-update-comment
on:
  workflow_call:
    inputs:
      comment-author:
        type: string
      body-includes:
        type: string
      body: 
        required: true
        type: string

jobs:
  create-update-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: ${{ inputs.comment-author }}
          body-includes: ${{ inputs.body-includes }}

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: $
          edit-mode: replace