name: Github to slack

on:
  pull_request:
  workflow_call:
    inputs:
      github_email:
        type: string
  workflow_dispatch:
    inputs:
      github_email:
        type: string
      

jobs:
  fetch:
    runs-on: ubuntu-latest
    outputs: 
      slack_user_id: steps.user_map.slack_user_name

    steps:
      - uses: actions/checkout@v4

      - name: Set slack user based on github user of code commiter
        id: user_map
        env:
          EMAIL: ${{ inputs.github_email }}
        run: |
          ./github_to_slack/github_to_slack.sh