name: Go test

on:
  workflow_call:
    inputs:
      go:
        type: string
        default: "1.17.x"
      mongo:
        type: string
      redis:
        type: string

jobs:
  gotest:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go }}
    - uses: actions/checkout@v3
    
    - name: Start Redis
      if: ${{ inputs.redis != '' }}
      uses: supercharge/redis-github-action@1.2.0
      with:
        redis-version: '${{ inputs.redis }}'

    - name: Start MongoDB
      if: ${{ inputs.mongo != '' }}
      uses: supercharge/mongodb-github-action@1.2.0
      with:
        mongodb-version: '${{ inputs.mongo }}'    
        
    - name: Cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    # Alternatively, install using go install
    - name: Set up gotestfmt
      run: go install github.com/haveyoudebuggedit/gotestfmt/v2/cmd/gotestfmt@latest
       
        
    - name: Go Test
      id: test
      run: |
        PKGS="$(go list ./...)"
        OPTS="$@"
        if [[ -z "$OPTS" ]]; then
          OPTS="-race -count=1 -failfast -v"
        fi
        
        for pkg in ${PKGS}; do
            tags=""
            if [[ ${pkg} == *"goplugin" ]]; then
                tags="-tags 'goplugin'"
            fi

            coveragefile=`echo "$pkg" | awk -F/ '{print $NF}'`

            echo go test ${OPTS} -timeout 15m -coverprofile=${coveragefile}.cov ${pkg} ${tags}
            set -euo pipefail
            go test ${OPTS} -timeout 15m -coverprofile=${coveragefile}.cov ${pkg} ${tags} | tee /tmp/gotest.log | gotestfmt
        done
    # Upload the original go test log as an artifact for later review.
    - name: Upload test log
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-log
        path: /tmp/gotest.log
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: "*cov"
