name: Go Vulnerability detection

on:
  workflow_call:

jobs:
  govulncheck:
    name: Go Vulnerability detection
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-go@v5.2.0

      - name: Govulncheck scan
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
