name: Go Vulnerability detection

on:
  workflow_call:

jobs:
  govulncheck:
    name: Go Vulnerability detection
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3
      - uses: actions/setup-go@be3c94b385c4f180051c996d336f57a34c397495  # v3

      - name: Govulncheck scan
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@v1.1.4  # d1f380186385b4f64e00313f31743df8e4b89a77
          govulncheck ./...
