name: JIRA linter

on:
  workflow_call:
    secrets:
      JIRA_TOKEN:
        required: true
      ORG_GH_TOKEN:
        required: true

jobs:
  jira-validation:
    runs-on: ubuntu-latest
    outputs:
      validation-report: ${{ steps.validate.outputs.report }}
      validation-status: ${{ steps.validate.outputs.status }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run Jira Validation
        id: validate
        uses: ./.github/actions/jira-lint
        with:
          github-token: ${{ secrets.ORG_GH_TOKEN }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: https://tyktech.atlassian.net
          skip-branches: '^(release-[0-9.-]+(lts)?|master|main)$'
          validate_issue_status: true
          skip-comments: true  # We'll handle comments in the next job

  create-comment:
    needs: jira-validation
    if: ${{ needs.jira-validation.outputs.validation-report != '' }}
    uses: ./.github/workflows/create-update-comment.yaml
    with:
      body-includes: "<!-- jira-lint-comment -->"
      body: ${{ needs.jira-validation.outputs.validation-report }}
