name: jira-lint
on: [pull_request]

jobs:
  jira-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: cleartax/jira-lint@master
        name: jira-lint
        with:
          github-token: ${{ secrets.ORG_GH_TOKEN }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: https://tyktech.atlassian.net/
          skip-branches: '^(release-[0-9.-]+(lts)?|master|main)$'
          validate_issue_status: true
          allowed_issue_statuses: "In Dev, In Progress, In Review"