name: jira-lint
on:
  workflow_call:
    secrets:
      JIRA_TOKEN:
        required: true
      ORG_GH_TOKEN:
        required: true

jobs:
  jira-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: cyrus-za/jira-lint@master 
        name: jira-lint
        with:
          github-token: ${{ secrets.ORG_GH_TOKEN }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: https://tyktech.atlassian.net/
          skip-branches: '^(release-[0-9.-]+(lts)?|master|main)$'
          validate_issue_status: true
          allowed_issue_statuses: "In Dev, In Code Review, Ready For Testing, In Test, In Progress, In Review"