name: PR Agent

on:
  workflow_call:
    inputs:
      dir:
        required: false
        type: string
    secrets:
      OPENAI_KEY:
        required: false
      GITHUB_TOKEN:
        required: false

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@v0.26
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
