name: Sbom

on:
  workflow_call:
    secrets:
      TF_API_TOKEN:
        required: true
      DOCKER_IMAGE:
        required: false
      DEPDASH_URL:
        required: true
      DEPDASH_KEY:
        required: true
      ORG_GH_TOKEN:
        required: true
    
jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      go: ${{ steps.changes.outputs.go }}
      npm: ${{ steps.changes.outputs.npm }}
      ci: ${{ steps.changes.outputs.ci }}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=go::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep go.mod$ | xargs)"
          echo "::set-output name=npm::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep package.json$ | xargs)"    
          echo "::set-output name=ci::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep ci/ | xargs)"
          echo "::set-output name=docker::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep Dockerfile | xargs)"
          echo "::set-output name=workflows::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep workflows | xargs)"
  sbom:
    name: SBOM
    runs-on: ubuntu-latest
    needs: changedfiles
    if: contains(github.ref, 'release-') || contains(github.ref, 'master') || needs.changedfiles.outputs.go || needs.changedfiles.outputs.npm || needs.changedfiles.outputs.ci || needs.changedfiles.outputs.docker || needs.changedfiles.outputs.workflows
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          token: ${{ secrets.ORG_GH_TOKEN }}
          submodules: true
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false
          
      - name: Get AWS creds from Terraform remote state
        id: aws-creds
        run: |
           cd ci/terraform
           terraform init -input=false
           terraform refresh 2>&1 >/dev/null
           eval $(terraform output -json ${GITHUB_REPOSITORY##*/} | jq -r 'to_entries[] | [.key,.value] | join("=")')
           region=$(terraform output region | xargs)
           [ -z "$key" -o -z "$secret" -o -z "$region" ] && exit 1
           echo "secret=$secret" >> $GITHUB_OUTPUT
           echo "key=$key" >> $GITHUB_OUTPUT
           echo "region=$region" >> $GITHUB_OUTPUT          

      - name: Configure AWS credentials for use
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ steps.aws-creds.outputs.key }}
          aws-secret-access-key: ${{ steps.aws-creds.outputs.secret }}
          aws-region: ${{ steps.aws-creds.outputs.region }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Generate Source code SBOM
        uses: aquasecurity/trivy-action@master
        with:
           scan-type: 'fs'
           format: 'cyclonedx'
           output: 'source.sbom.json'
           image-ref: '.'

      - name: Generate Docker SBOM
        uses: aquasecurity/trivy-action@master
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
        if: env.DOCKER_IMAGE == null
        with:
          format: 'cyclonedx'
          output: 'docker.sbom.json'
          image-ref: '${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name}}:${{ github.sha }}'
          
      - name: Generate Docker SBOM
        uses: aquasecurity/trivy-action@master
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
        if: env.DOCKER_IMAGE
        with:
          format: 'cyclonedx'
          output: 'docker.sbom.json'
          image-ref: '${{ secrets.DOCKER_IMAGE }}'


      - name: Generate Dependencies SBOM
        run: |
          curl https://raw.githubusercontent.com/TykTechnologies/github-actions/main/sbom/gen_dep.py > gen_dep.py
          python3 gen_dep.py service.yaml > deps.sbom.json

      - name: Merge SBOM
        run: |
          curl https://raw.githubusercontent.com/TykTechnologies/github-actions/main/sbom/merge.py > merge.py
          python3 merge.py source.sbom.json docker.sbom.json deps.sbom.json > sbom.json
      
      - name: Upload SBOM
        run: |
           if [ -n "$GITHUB_HEAD_REF" ]; then
             BRANCH_NAME="${GITHUB_HEAD_REF##*/}"
           else
             BRANCH_NAME="${GITHUB_REF##*/}"
           fi
            
           curl '${{secrets.DEPDASH_URL}}/api/v1/bom' -X 'POST' -H 'X-API-Key: ${{secrets.DEPDASH_KEY}}' -H "Content-Type: multipart/form-data" -F "autoCreate=true" -F "projectName=${GITHUB_REPOSITORY##*/}" -F "projectVersion=${BRANCH_NAME}" -F "bom=@./sbom.json" -vvv
           
           # curl -vvv '${{secrets.DEPDASH_URL}}/api/v1/project/lookup?name=${GITHUB_REPOSITORY##*/}&version=${BRANCH_NAME}' -H 'X-API-Key: ${{secrets.DEPDASH_KEY}}
           # PROJECT_UUID=$(curl --silent '${{secrets.DEPDASH_URL}}/api/v1/project/lookup?name=${GITHUB_REPOSITORY##*/}&version=${BRANCH_NAME}' -H 'X-API-Key: ${{secrets.DEPDASH_KEY}}' | jq -r .uuid)
