name: Sbom

on:
  workflow_call:
    secrets:
      TF_API_TOKEN:
        required: true
      DEPDASH_URL:
        required: true
      DEPDASH_KEY:
        required: true
    
jobs:
  sbom:
    name: SBOM
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      - name: Get AWS creds from Terraform remote state
        id: aws-creds
        run: |
          cd ci/terraform
          terraform init -input=false
          terraform refresh 2>&1 >/dev/null
          eval $(terraform output -json tyk-analytics | jq -r 'to_entries[] | [.key,.value] | join("=")')
          region=$(terraform output region | xargs)
          [ -z "$key" -o -z "$secret" -o -z "$region" ] && exit 1
          echo "secret=$secret" >> $GITHUB_OUTPUT
          echo "key=$key" >> $GITHUB_OUTPUT
          echo "region=$region" >> $GITHUB_OUTPUT
        
      - name: Configure AWS credentials for use
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ steps.aws-creds.outputs.key }}
          aws-secret-access-key: ${{ steps.aws-creds.outputs.secret }}
          aws-region: ${{ steps.aws-creds.outputs.region }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Generate Source code SBOM
        uses: aquasecurity/trivy-action@master
        with:
           scan-type: 'fs'
           format: 'cyclonedx'
           output: 'source.sbom.json'
           image-ref: '.'

      - name: Generate Docker SBOM
        uses: aquasecurity/trivy-action@master
        with:
          format: 'cyclonedx'
          output: 'docker.sbom.json'
          image-ref: '${{ steps.login-ecr.outputs.registry }}/tyk-analytics:${{ github.sha }}'

      - name: Generate Dependencies SBOM
        run: |
          curl https://raw.githubusercontent.com/TykTechnologies/github-actions/main/sbom/gen_dep.py > gen_dep.py
          python3 gen_dep.py service.yaml > deps.sbom.json

      - name: Merge SBOM
        run: |
          curl https://raw.githubusercontent.com/TykTechnologies/github-actions/main/sbom/merge.py > merge.py
          python3 merge.py source.sbom.json docker.sbom.json deps.sbom.json > sbom.json
      
      - name: Upload SBOM
        run: |
           echo "${{GITHUB_REF##*/}}"
           echo "${{GITHUB_REF}}"
           curl '${{secrets.DEPDASH_URL}}/api/v1/bom' -X 'POST' -H 'X-API-Key: ${{secrets.DEPDASH_KEY}}' -H "Content-Type: multipart/form-data" -F "autoCreate=true" -F "projectName=${GITHUB_REPOSITORY##*/}" -F "projectVersion=${GITHUB_REF##*/}" -F "bom=@./sbom.json" -vvv
