name: Sbom

on:
  workflow_call:
    secrets:
      TF_API_TOKEN:
        required: true
      DEPDASH_URL:
        required: true
      DEPDASH_KEY:
        required: true
      ORG_GH_TOKEN:
        required: true
    
jobs:
  sbom:
    name: SBOM
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          token: ${{ secrets.ORG_GH_TOKEN }}
          submodules: true

      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::754489498669:role/ecr_rw_tyk
          role-session-name: cipush
          aws-region: eu-central-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate Source code SBOM
        uses: aquasecurity/trivy-action@master
        with:
           scan-type: 'fs'
           format: 'cyclonedx'
           output: 'source.sbom.json'
           image-ref: '.'

      - name: Generate Docker SBOM
        uses: aquasecurity/trivy-action@master
        with:
          format: 'cyclonedx'
          output: 'docker.sbom.json'
          image-ref: '${{ steps.login-ecr.outputs.registry }}/tyk-analytics:${{ github.sha }}'

      - name: Generate Dependencies SBOM
        run: |
          curl https://raw.githubusercontent.com/TykTechnologies/github-actions/main/sbom/gen_dep.py > gen_dep.py
          python3 gen_dep.py service.yaml > deps.sbom.json

      - name: Merge SBOM
        run: |
          curl https://raw.githubusercontent.com/TykTechnologies/github-actions/main/sbom/merge.py > merge.py
          python3 merge.py source.sbom.json docker.sbom.json deps.sbom.json > sbom.json
      
      - name: Upload SBOM
        run: |
           echo "${GITHUB_HEAD_REF##*/}"
           echo "${GITHUB_HEAD_REF}"
           curl '${{secrets.DEPDASH_URL}}/api/v1/bom' -X 'POST' -H 'X-API-Key: ${{secrets.DEPDASH_KEY}}' -H "Content-Type: multipart/form-data" -F "autoCreate=true" -F "projectName=${GITHUB_REPOSITORY##*/}" -F "projectVersion=${GITHUB_HEAD_REF##*/}" -F "bom=@./sbom.json" -vvv
