name: "Semgrep scan"

on:
  workflow_call:
    inputs:
      config:
        default: "auto"
        type: string

jobs:
  semgrep:
    name: Semgrep
    runs-on: ubuntu-20.04

    outputs:
      scan: ${{ steps.scan.outputs.test }}

    container:
      image: returntocorp/semgrep

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3

      - name: Semgrep scan
        id: scan
        run: |
          semgrep --config ${{ inputs.config }} --output semgrep-report.txt --error --exclude=docs
    
      - name: Archive Semgrep report
        if: ${{ always() }}
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5  # v3
        with:
          name: semgrep-report.txt
          path: semgrep-report.txt
