name: "Semgrep scan"

on:
  workflow_call:
    inputs:
      config:
        default: "auto"
        type: string

jobs:
  semgrep:
    name: Semgrep
    runs-on: ubuntu-20.04

    outputs:
      scan: ${{ steps.scan.outputs.test }}

    container:
      image: returntocorp/semgrep

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4.2.2

      - name: Semgrep scan
        id: scan
        run: |
          semgrep --config ${{ inputs.config }} --output semgrep-report.txt --error --exclude=docs
    
      - name: Archive Semgrep report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4.5.0
        with:
          name: semgrep-report.txt
          path: semgrep-report.txt
