---
name: zizmor self-scan

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  zizmor:
    uses: ./.github/workflows/zizmor.yml
    permissions:
      security-events: write
      contents: read
      actions: read
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
